version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
